export const environment = {
  production: true,
  apiUrl: "http://localhost:8080/",
  apiEndpoints: {
    users: "users/",
    login: "login",
    logout: "logout-user",
    forgotPassword: "forgot-password",
    resetPassword: "reset-password",
    findAccount: "find-account",
    findEmail: "find-email/",
    userPage:"users/page",
    userPageFilter:"users/page/filter",
    theatres: "theatres/",
    theatrePage:"theatres/page",
    theatrePageFilter:"theatres/page/filter",
    movies: "movies/",
    moviePage:"movies/page",
    moviePageFilter:"movies/page/filter",
    movieTheatreDay: "movies/movies-and-times",
    showTimings: "show-timings",
    showTimingsPage:"show-timings/page",
    showTimingsPageFilter:"show-timings/page/filter",
    dashboard: "users/dashboard",
    currentRunning: "movies/current-running",
    soonRunning: "movies/soon-running",
    theatreLocations: "theatres/locations",
    theatresFilterd: "theatres/filtered/",
    venues: "venues/",
    venuesPage:"venues/page",
    venuesPageFilter:"venues/page/filter"
  }
};
